In [1]:
import numpy as np

In [2]:
from scipy import stats

In [3]:
akash=np.array([4,8,4,1,59,23])
akash

array([ 4,  8,  4,  1, 59, 23])

In [4]:
print(np.mean(akash))

16.5


In [5]:
mean = np.mean(akash)  # Alternate way
mean

16.5

In [6]:
print(np.median(akash))

6.0


In [7]:
print(stats.mode(akash))

ModeResult(mode=array([4]), count=array([2]))


In [8]:
akash1=np.array([12,46,23,87,32,54])
akash1

array([12, 46, 23, 87, 32, 54])

In [9]:
print(np.mean(akash1))

42.333333333333336


In [10]:
print(np.median(akash))

6.0


In [11]:
print(stats.mode(akash1))

ModeResult(mode=array([12]), count=array([1]))


In [12]:
akash2=np.array([34,23,67,221,453,23])
akash2

array([ 34,  23,  67, 221, 453,  23])

In [13]:
print(np.mean(akash2))

136.83333333333334


In [14]:
print(np.median(akash2))

50.5


In [15]:
print(stats.mode(akash2))

ModeResult(mode=array([23]), count=array([2]))


In [16]:
akash3=np.array([43,65,789,432,1246,5433,43,65,789,342])
akash3

array([  43,   65,  789,  432, 1246, 5433,   43,   65,  789,  342])

In [17]:
print(np.mean(akash3))
print(np.median(akash3))
print(stats.mode(akash3))

924.7
387.0
ModeResult(mode=array([43]), count=array([2]))


In [18]:
print(np.std(akash))



20.303940504246953


In [19]:
print(np.std(akash1))

24.30820620467271


In [20]:
print(np.std(akash2))

157.27514813924742


In [21]:
print(np.std(akash3))

1551.7758246602502


In [22]:
np.var(akash)

412.25

In [23]:
np.var(akash1)

590.8888888888888

In [24]:
np.var(akash2)

24735.47222222222

In [25]:
np.var(akash3)

2408008.21