# Numpy: Package for Multidimentional array
## Vector(1-D)
## 3rd/2nd/1st - Oeder Matrix

In [1]:
import numpy as np   #Importing numerical python as np

In [2]:
Akash_list=[3,1,6]                     #Converting from list to array
np.array(Akash_list)

array([3, 1, 6])

In [3]:
Akash_array=np.array([5,6,1])    # Direct way of getting array
Akash_array

array([5, 6, 1])

In [4]:
Akash_lists=[[8,5,2],[1,7,3],[9,3,5]]
np.array(Akash_lists)

array([[8, 5, 2],
       [1, 7, 3],
       [9, 3, 5]])

In [5]:
Akash_lists1=([8,5,2],[1,7,3],[9,3,5])
np.array(Akash_lists)

array([[8, 5, 2],
       [1, 7, 3],
       [9, 3, 5]])

In [6]:
Akash_lists2=[8,5,2],[1,7,3],[9,3,5]
np.array(Akash_lists)

array([[8, 5, 2],
       [1, 7, 3],
       [9, 3, 5]])

In [7]:
Akash_array1=np.array([[1,2,3],[4,5,6]])
Akash_array1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
Akash_lists3=np.array([[8,5,2],[1,7,3],[9,3,5]])   #Direct way of getting array
Akash_lists3

array([[8, 5, 2],
       [1, 7, 3],
       [9, 3, 5]])

In [9]:
np.arange(4,27)    #this fuction gives output starting from 1st number i.e 4 with step size as 1(default if not mention) and
                  # ends just before 2nd number (27 will not be there in the output)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26])

In [10]:
np.arange(7,1245,53)     #step size is 53

array([   7,   60,  113,  166,  219,  272,  325,  378,  431,  484,  537,
        590,  643,  696,  749,  802,  855,  908,  961, 1014, 1067, 1120,
       1173, 1226])

In [11]:
np.zeros(9)          # To get zeros (float is default setting)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(9,dtype=int)    #To get integer

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(3)       # To get ones 

array([1., 1., 1.])

In [14]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [15]:
np.ones((4,8),dtype=int)  # 4 row and 8 column

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [16]:
np.linspace(4,9,6)      # starts with 4 and ends with 9 with 6 equally spaced output

array([4., 5., 6., 7., 8., 9.])

In [17]:
np.linspace(1,220,17)

array([  1.    ,  14.6875,  28.375 ,  42.0625,  55.75  ,  69.4375,
        83.125 ,  96.8125, 110.5   , 124.1875, 137.875 , 151.5625,
       165.25  , 178.9375, 192.625 , 206.3125, 220.    ])

In [18]:
np.linspace(1,32,3)

array([ 1. , 16.5, 32. ])

In [19]:
np.eye(3,dtype=int)  ## indentity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
np.random.rand(3,2)    # 2*4 matrix with random values between [0,1) Uniform distribution. 

array([[0.66805758, 0.73979   ],
       [0.67732074, 0.69464307],
       [0.93236781, 0.75078474]])

In [21]:
np.random.randn(4,7)      # 4*7 matrix with random values normal distribution

array([[-0.52094403,  0.15296237, -1.40878941, -0.23046005, -0.44761899,
        -0.95548282, -0.55085711],
       [ 0.12160194,  1.42628841, -1.09220991,  0.84408981, -1.08798335,
        -0.69260716, -1.53611214],
       [ 0.48170349,  1.39992458, -0.96054934, -0.77367936, -1.14347354,
        -0.01413848, -1.21744384],
       [ 0.16898677, -0.37267541, -0.17985749,  0.82734049, -0.9598437 ,
        -0.8103799 , -0.43722054]])

In [22]:
np.random.randint(0,20,50)   # 15 Random output from 0 to 19. And repetition is allowed.

array([ 0, 14,  5, 19,  5, 12, 14, 11, 19,  0, 14, 14, 13, 16,  6,  4,  3,
       16,  0,  8, 11,  8,  7, 11,  6, 10, 12, 19,  2, 10,  3, 16,  3, 15,
       19, 16, 12,  5,  5,  5, 11,  3,  9, 17, 19, 16, 15, 18, 10,  0])

In [23]:
np.random.randint(23,76,15)

array([67, 47, 75, 52, 45, 43, 30, 37, 45, 40, 69, 41, 75, 63, 26])

In [24]:
np.random.randint(10,46,100)

array([45, 11, 34, 32, 18, 29, 22, 40, 37, 32, 18, 43, 19, 26, 32, 41, 35,
       32, 14, 13, 10, 31, 31, 37, 27, 15, 35, 20, 41, 38, 33, 24, 29, 18,
       35, 45, 28, 21, 28, 24, 32, 18, 45, 30, 35, 40, 23, 36, 30, 32, 37,
       38, 36, 21, 13, 21, 11, 26, 31, 15, 18, 19, 23, 28, 39, 17, 43, 21,
       31, 36, 44, 35, 18, 10, 18, 35, 42, 28, 45, 40, 19, 17, 26, 23, 37,
       20, 17, 30, 21, 44, 29, 33, 42, 42, 12, 36, 16, 43, 33, 34])

In [25]:
Akash_array3=np.arange(21,54)
Akash_array3

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53])

In [26]:
Akash_rand_array=np.random.randint(2,19,12)
Akash_rand_array

array([14, 10,  5,  4, 13, 12,  6, 13, 14,  4, 11,  3])

In [27]:
Akash_array3.min()    # MINIMUM VALUE

21

In [28]:
Akash_array3.argmin()   # Index of minimum value

0

In [29]:
Akash_array3.max()  # Maximum value

53

In [30]:
Akash_array3.argmax()   # Index of maximum value

32

In [31]:
Akash_rand_array.min()

3

In [32]:
Akash_rand_array.argmin()

11

In [33]:
Akash_rand_array.max()

14

In [34]:
Akash_rand_array.argmax()

0

In [35]:
Akash_array.dtype

dtype('int32')

In [36]:
Q=np.eye(3)
Q

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
Q=np.random.rand(3,4)
Q

array([[0.97100136, 0.4424818 , 0.20071579, 0.25867901],
       [0.34009531, 0.42374701, 0.52142952, 0.86638983],
       [0.29058692, 0.9903867 , 0.70034103, 0.86976826]])

In [38]:
Q.T  # Transpose of matrix Q

array([[0.97100136, 0.34009531, 0.29058692],
       [0.4424818 , 0.42374701, 0.9903867 ],
       [0.20071579, 0.52142952, 0.70034103],
       [0.25867901, 0.86638983, 0.86976826]])

In [39]:
Akash_array4=np.arange(14,30)
Akash_array4

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
Akash_array4=Akash_array4.reshape(4,4)
Akash_array4

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [41]:
Akash_array4=sample_array.reshape(3,4)  # There are 8 values only so the multiplication of order of the matrix should be 8 only.
Akash_array4

NameError: name 'sample_array' is not defined

In [42]:
Akash_array4[3]=100    # Mutation property 4rd row (index 0 is 1st raw) will get change. 
Akash_array4

array([[ 14,  15,  16,  17],
       [ 18,  19,  20,  21],
       [ 22,  23,  24,  25],
       [100, 100, 100, 100]])

In [43]:
Akash_array5=np.arange(13,49)
Akash_array5

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48])

In [44]:
Akash_array5[4:16]    #  start from index 4 ends at index 15 (consider 0 index)  

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [45]:
Akash_array6=Akash_array5[2:9]     # index 2 to index 8
Akash_array6

array([15, 16, 17, 18, 19, 20, 21])

In [46]:
Akash_array5[:]=123   # : means all element will become 123
Akash_array5

array([123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123,
       123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123,
       123, 123, 123, 123, 123, 123, 123, 123, 123, 123])

### two dimensional array

In [47]:
import numpy as np

In [48]:
Akash_matrix=np.array([[12,13,4,21],[32,8,5,32],[5,3,6,5]])
Akash_matrix

array([[12, 13,  4, 21],
       [32,  8,  5, 32],
       [ 5,  3,  6,  5]])

In [49]:
Akash_matrix[2][1]    # calling 2nd row 1st column  (Remember row and column starts with zero)

3

In [50]:
Akash_matrix[0][1]

13

In [51]:
Akash_matrix[:,1]     # ':' means all rows 

array([13,  8,  3])

In [52]:
Akash_matrix[2,0]

5

In [53]:
Akash_matrix[0:2,0:3]   # 0:2 means row = 0,1 and 0:3 means column = 0,1,2  (comman between row and column)

array([[12, 13,  4],
       [32,  8,  5]])

In [54]:
Akash_matrix[1:,0:]    # 1: means from 1st row onwards 
                       # 0: means from 2nd column onwards

array([[32,  8,  5, 32],
       [ 5,  3,  6,  5]])

In [55]:
Akash_matrix[1]   # 1st row

array([32,  8,  5, 32])

In [56]:
Akash_array7=np.arange(5,42)       
Akash_array7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41])

In [57]:
Akash_array7+Akash_array7  # Summation

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82])

In [58]:
np.exp(Akash_array7)   # exponential of all element which is stored in Akash_array7 

array([1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
       2.14643580e+14, 5.83461743e+14, 1.58601345e+15, 4.31123155e+15,
       1.17191424e+16, 3.18559318e+16, 8.65934004e+16, 2.35385267e+17,
       6.39843494e+17])

In [59]:
np.sqrt(Akash_array7)  # Squart root of all element which is stored in Akash_array7 

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424])

In [60]:
np.log(Akash_array7) #Logirithm of all element which is stored in Akash_array7

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207])

In [61]:
np.max(Akash_array7)

41

In [62]:
np.min(Akash_array7)

5

In [63]:
np.argmax(Akash_array7) # Index of maximum number

36

In [64]:
np.argmin(Akash_array7) # Index of minimum number

0

In [65]:
np.square(Akash_array7)  # Square of all element which is stored in Akash_array7

array([  25,   36,   49,   64,   81,  100,  121,  144,  169,  196,  225,
        256,  289,  324,  361,  400,  441,  484,  529,  576,  625,  676,
        729,  784,  841,  900,  961, 1024, 1089, 1156, 1225, 1296, 1369,
       1444, 1521, 1600, 1681], dtype=int32)

In [66]:
np.std(Akash_array7)  # Standard deviation  

10.677078252031311

In [67]:
np.var(Akash_array7)  # Variance

114.0

In [68]:
np.mean(Akash_array7)  # Mean

23.0

In [69]:
Akash=np.random.randn(3,4)  ### normal distribution. random matrix 3*4
Akash

array([[-0.01590616, -0.67636978,  0.78526238, -1.75648516],
       [ 0.06585092,  1.24764424, -0.91954745, -0.67744803],
       [ 0.6675886 ,  0.10995795,  1.32609057, -0.19868499]])

In [70]:
np.round(Akash,decimals=3)  # Rounding off up to 3 places

array([[-0.016, -0.676,  0.785, -1.756],
       [ 0.066,  1.248, -0.92 , -0.677],
       [ 0.668,  0.11 ,  1.326, -0.199]])

In [71]:
names=np.array(['akash','nishad','tuba','kapil','akash','nishad','jigar'])  # it will consider only unique values
np.unique(names)

array(['akash', 'jigar', 'kapil', 'nishad', 'tuba'], dtype='<U6')